[workspace]
authors = ["Yoav Ram <yoav@yoavram.com>"]
channels = ["conda-forge"]
name = "DataSciPy"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.3.*"
scikit-image = ">=0.25.2,<0.26"

[pypi-dependencies]
corner = ">=2.2.3, <3"
imageio = "*"
ipywidgets = ">=8.1.8, <9"
jax = ">=0.8.0, <0.9"
keras = ">=3.12.0, <4"
matplotlib = ">=3.10.7, <4"
numpy = ">=2.3.4, <3"
optax = ">=0.2.6, <0.3"
palmerpenguins = ">=0.1.4, <0.2"
pandas = ">=2.3.3, <3"
scipy = ">=1.16.3, <2"
seaborn = ">=0.13.2, <0.14"
statsmodels = ">=0.14.5, <0.15"
jupyterlab = ">=4.4.10, <5"
pip = ">=25.3, <26"
scikit-learn = ">=1.7.2, <2"
